### ISSUE TITLE
Error while running node 

### ISSUE THREAD

**Issue by rayanaravikumar** [dab00/mongodb-es-river#1]
Getting below error when i ran the app
E:\nodeserver>node app.js

E:\nodeserver\node_modules\mongodb\lib\server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

my app.js file is as below

var mongodb = require('mongodb');
var local = 'mongodb://localhost:27001,localhost:27002/local?replicaSet=x&readPreference=secondaryPreferred';
var test = 'mongodb://localhost:27001,localhost:27002/test?replicaSet=x';
 
mongodb.connect(local, function(err, localDb) {
  if (err) throw err;
  mongodb.connect(test, function(err, testDb) {
    if (err) throw err;
    var settings = {
      oplog: localDb.collection('oplog.rs'), // required
      registry: testDb.collection('river'), // required
      client: require('elasticsearch').Client() // required
    };
    var options = [
      {
        index: 'test', // required
        type: 'users', // required
        collection: testDb.collection('users'), // required
        project: {name: 1, fullName: 1} // optional
      },
    ];
    require('mongodb-es-river')(settings, options, function(err) {
      if (err) throw err;
      console.log('All rivers run, pid:', process.pid);
    });
  });
});

**Comment by dab00** [comment]
Are you sure you have got replicaSet "x" on localhost:27001,localhost:27002?
